"""Add Budget model

Revision ID: 79a583b66a58
Revises: 9a93a5acdcf8
Create Date: 2025-10-12 10:54:20.569676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a583b66a58'
down_revision = '9a93a5acdcf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food', sa.Float(), nullable=True),
    sa.Column('transport', sa.Float(), nullable=True),
    sa.Column('study', sa.Float(), nullable=True),
    sa.Column('entertainment', sa.Float(), nullable=True),
    sa.Column('others', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget')
    # ### end Alembic commands ###
